username: 
password: 
phone_number: 

profile_path: 'C:\\Users\\pc\\Desktop\\chromedriver-win64\\chromedriver.exe' #can be empty, will default to 'C:\Users\<user>\AppData\Local\Google\Chrome\User Data\Default'


positions:
- 
# - <position title 2>
# - <position title 3>


locations:
# - <state>
- pakistan

salary: 50000
rate: 10
# --------- Optional Parameters -------
uploads:
  Resume: "C:\\Users\\pc\\Desktop\\LinkedIn-Easy-Apply-Bot-master\\myresume.pdf"
  Cover Letter: "C:\\Users\\pc\\Desktop\\LinkedIn-Easy-Apply-Bot-master\\myresume.pdf"
  #Photo: # PATH TO photo


output_filename:
- "C:\\Users\\pc\\Desktop\\LinkedIn-Easy-Apply-Bot-master\\out.csv" # PATH TO OUTPUT FILE (default output.csv)

# blacklist:
# - # Company names you want to ignoreclc
